# Generated by Django 2.2.13 on 2020-07-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendeur_accounts', '0002_auto_20200710_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='cover',
            field=models.ImageField(null=True, upload_to='photo/'),
        ),
    ]
